name: flutter_bloc_architecture
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  flutter_bloc: ^6.1.2
  intl: ^0.17.0
  path_provider: ^1.1.0
  progress_dialog: 1.2.1
  fluttertoast: ^3.1.3
  # To open the url
  url_launcher: 5.4.2

  # Used for dependency injection
  get_it: 4.0.1

  #Creates an automated routing class
  auto_route: 0.3.1
  toast: ^0.1.5

  # flutter_platform_widgets will display the widget for both platform seperately
  flutter_platform_widgets: 0.32.4
  equatable: 1.1.1
  wave: ^0.0.8

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

  # The following adds the shared pref as a dependency in your application
  shared_preferences: ^0.5.6+3

  # A composable, Future-based library for making HTTP requests.
  http: ^0.12.0+2

  # The following adds the launcher icon support to your application.
  # run below mentioned commands to generate launcher icons
  # flutter packages get
  # flutter packages pub run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.7.4

  #a powerful logging framework
  logger: ^0.8.3

  # String validation and sanitization for Dart. Dart 2-compatible version of validator
  validators: ^2.0.0+1

  # A powerful Http client for Dart
  dio: 3.0.8

  # A flexible widget for user notification.
  flushbar: ^1.9.1

  # Material Dialog
  material_dialog: ^0.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 0.3.2
  json_serializable: ^3.2.3
  retrofit_generator: ^1.0.1
  # of course build_runner is needed to run the generator
  build_runner:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/powered_by.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans-Bold
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf

    - family: OpenSans-Light
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf

    - family: OpenSans-Regular
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf

    - family: OpenSans-Semibold
      fonts:
        - asset: assets/fonts/OpenSans-Semibold.ttf

    - family: Muli-Bold
      fonts:
        - asset: assets/fonts/Muli-Bold.ttf

    # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages